jobs:
  install_models:
    runs-on:
    - blogin3 
    strategy:
      fail-fast: false
      matrix:
        model:
        - foci-default 
        #- focioifs-2.0
    steps:
    - uses: actions/checkout@v2
    - name: Compile Model
      run: 'module load git
        module load anaconda3/2019.10
        pwd
        rm -rf env
        python -m venv env_esm_tools
        source env/bin/activate
        python --version
        pip --version
        cp -pv ~/.esmtoolsrc ~/.esmtoolsrc_ci_backup
        pip install .
        rm -rf ${GITHUB_WORKSPACE}/models/${{ matrix.model }}
        mkdir -p ${GITHUB_WORKSPACE}/models
        cd ${GITHUB_WORKSPACE}/models
        esm_master install-${{ matrix.model }}
        cp -v ~/.esmtoolsrc ~/.esmtoolsrc_ci # save for next job
        cp -v ~/.esmtoolsrc_ci_backup ~/.esmtoolsrc
        '
    #- if: ${{ always() }}
    #  name: Cleanup venv
    #  run: 'rm -rf env'
        
  run_models:        
    runs-on:
    - blogin3 
    needs: install_models
    strategy:
      fail-fast: false
      matrix:
        model:
        - foci-default 
    steps:
    - name: Run Test Simulation 
      run: 'module load git
        module load anaconda3/2019.10
        source env_esm_tools/bin/activate
        python --version
        pip --version
        cp -v ~/.esmtoolsrc_ci ~/.esmtoolsrc
        pwd
        ls -lh 
        cd ${GITHUB_WORKSPACE}/esm_tools/runscripts/foci/
        esm_runscripts -e foci-default-ci foci-blogin-initial-piCtl-daily-restart.yaml 
        logfile="${GITHUB_WORKSPACE}/esm-experiments/foci-default-ci/log/focitest0_foci.log"
        while [ true ] ; do
          if [[ ! -f ${logfile} ]] ; then
            # TODO: do a grep for submitted, grep for JOBID and extend
            # waiting time if job is in pending state
            # once in running state run a timer and exit with error if job takes more than 5 minutes 
            # to complete
            if grep -q "Experiment over" ${logfile} ; then
              echo "Experiment finished successfully"
              break
            else
              sleep 10s
            fi  
          else
            sleep 10s
          fi
        done
        cp -v ~/.esmtoolsrc_ci_backup ~/.esmtoolsrc
        '
name: CI-blogin-install-foci-default
'on':
  pull_request:
    branches:
    - release
    - develop
    - '*prep-release*'
    paths:
    - configs/setups/foci.yaml
    - configs/components/xios.yaml
    - configs/components/echam.yaml
    - configs/components/nemo.yaml
    - configs/components/oasis3mct/oasis3mct.yaml
    - configs/couplings/nemo-ORCA05_LIM2_KCM_AOW+echam-6.3.05p2-foci.yaml
  push:
    branches:
    - release
    - develop
    - '*prep-release*'
    paths:
    - configs/setups/foci.yaml
    - configs/components/xios.yaml
    - configs/components/echam.yaml
    - configs/components/nemo.yaml
    - configs/components/oasis3mct/oasis3mct.yaml
    - configs/couplings/nemo-ORCA05_LIM2_KCM_AOW+echam-6.3.05p2-foci.yaml
